# Generated by Django 5.2.7 on 2026-07-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_id_alter_category_id_alter_color_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabric_and_care',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fitting',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_and_return',
            field=models.TextField(blank=True),
        ),
    ]
