# Generated by Django 6.0.7 on 2026-07-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_id_alter_category_id_alter_color_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_modiweek',
            field=models.BooleanField(default=False),
        ),
    ]
