# Generated by Django 6.0.7 on 2026-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('collection_kurti', 'Collection — Kurti'), ('collection_shrugs', 'Collection — Shrugs'), ('collection_saree', 'Collection — Saree'), ('collection_kameez', 'Collection — Kameez'), ('sustainability', 'Sustainability Banner')], max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/site-banners/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
