# Generated by Django 6.0.7 on 2026-07-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_sitebanner_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='key',
            field=models.CharField(choices=[('collection_kurti', 'Collection — Kurti'), ('collection_shrugs', 'Collection — Shrugs'), ('collection_saree', 'Collection — Saree'), ('collection_kameez', 'Collection — Kameez'), ('sustainability', 'Sustainability Banner'), ('hero_slide_1', 'Hero — Slide 1'), ('hero_slide_2', 'Hero — Slide 2'), ('hero_slide_3', 'Hero — Slide 3'), ('modiweek_feature', 'Modiweek — Feature Look'), ('sustainability_hero', 'Sustainability — Hero Image'), ('sustainability_processing', 'Sustainability — Processing'), ('sustainability_materials', 'Sustainability — Materials'), ('sustainability_packaging', 'Sustainability — Packaging'), ('sustainability_product_caring', 'Sustainability — Product Caring'), ('sustainability_team_1', 'Sustainability — Team Photo 1'), ('sustainability_team_2', 'Sustainability — Team Photo 2'), ('sustainability_team_3', 'Sustainability — Team Photo 3'), ('sustainability_team_4', 'Sustainability — Team Photo 4'), ('sustainability_team_5', 'Sustainability — Team Photo 5'), ('sustainability_team_6', 'Sustainability — Team Photo 6')], max_length=50, unique=True),
        ),
    ]
