# Generated by Django 6.0.7 on 2026-07-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_sitebanner_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPage',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
