# Generated by Django 6.0.7 on 2026-07-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_sitebanner_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebanner',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='cta_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='key',
            field=models.CharField(choices=[('collection_kurti', 'Collection — Kurti'), ('collection_shrugs', 'Collection — Shrugs'), ('collection_saree', 'Collection — Saree'), ('collection_kameez', 'Collection — Kameez'), ('sustainability', 'Sustainability Banner'), ('our_story', 'Our Story — Homepage Band'), ('hero_slide_1', 'Hero — Slide 1'), ('hero_slide_2', 'Hero — Slide 2'), ('hero_slide_3', 'Hero — Slide 3'), ('hero_slide_1_mobile', 'Hero — Slide 1 (Mobile)'), ('hero_slide_2_mobile', 'Hero — Slide 2 (Mobile)'), ('hero_slide_3_mobile', 'Hero — Slide 3 (Mobile)'), ('modiweek_feature', 'Modiweek — Feature Look'), ('shop_hero', 'Shop All — Hero Banner'), ('shop_hero_mobile', 'Shop All — Hero Banner (Mobile)'), ('sustainability_hero', 'Sustainability — Hero Image'), ('sustainability_processing', 'Sustainability — Processing'), ('sustainability_materials', 'Sustainability — Materials'), ('sustainability_packaging', 'Sustainability — Packaging'), ('sustainability_product_caring', 'Sustainability — Product Caring'), ('sustainability_team_1', 'Sustainability — Team Photo 1'), ('sustainability_team_2', 'Sustainability — Team Photo 2'), ('sustainability_team_3', 'Sustainability — Team Photo 3'), ('sustainability_team_4', 'Sustainability — Team Photo 4'), ('sustainability_team_5', 'Sustainability — Team Photo 5'), ('sustainability_team_6', 'Sustainability — Team Photo 6'), ('megamenu_collection_1', 'Mega Menu — Collection Tile 1'), ('megamenu_collection_2', 'Mega Menu — Collection Tile 2'), ('megamenu_new_in_1', 'Mega Menu — New In Tile 1'), ('megamenu_new_in_2', 'Mega Menu — New In Tile 2'), ('megamenu_new_in_3', 'Mega Menu — New In Tile 3'), ('megamenu_modiweek_1', 'Mega Menu — Modiweek Tile 1'), ('megamenu_modiweek_2', 'Mega Menu — Modiweek Tile 2'), ('megamenu_sustainability_1', 'Mega Menu — Sustainability Tile 1'), ('megamenu_sustainability_2', 'Mega Menu — Sustainability Tile 2')], max_length=50, unique=True),
        ),
    ]
