# Generated by Django 6.0.7 on 2026-07-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_id_alter_customerprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
