# Generated by Django 6.0.7 on 2026-07-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, default='Loomino', max_length=120)),
                ('app_url', models.URLField(blank=True)),
                ('email_address', models.EmailField(blank=True, help_text='Public business email shown on the storefront.', max_length=254)),
                ('admin_notification_email', models.EmailField(blank=True, help_text='Where new-order and system notifications are sent.', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Official WhatsApp / contact number.', max_length=30)),
                ('hotline_number', models.CharField(blank=True, max_length=30)),
                ('currency_name', models.CharField(blank=True, default='BDT', max_length=10)),
                ('currency_symbol', models.CharField(blank=True, default='৳', max_length=8)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, help_text='Flat delivery charge applied to every order.', max_digits=10)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('privacy_policy_link', models.CharField(blank=True, max_length=300)),
                ('terms_conditions_link', models.CharField(blank=True, max_length=300)),
                ('service_hours', models.CharField(blank=True, help_text='Service hours / footer text.', max_length=200)),
                ('physical_address', models.TextField(blank=True)),
                ('google_map_embed_url', models.TextField(blank=True, help_text='The src URL from a Google Maps embed iframe.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
