# Generated by Django 6.0.7 on 2026-07-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_cart_id_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_refund_status',
            field=models.CharField(choices=[('none', 'None'), ('cancel_requested', 'Cancel Requested'), ('refund_requested', 'Refund Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=30),
        ),
    ]
