# Generated by Django 6.0.7 on 2026-07-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_cancel_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('sslcommerz', 'SSL Gateway')], max_length=20),
        ),
    ]
