# Generated by Django 4.2.30 on 2026-07-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_cart_id_alter_cartitem_id_alter_order_id_and_more'),
        ('orders', '0012_alter_payment_payment_method'),
    ]

    operations = [
    ]
