# Generated by Django 4.2.30 on 2026-07-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_merge_20260721_1234'),
        ('orders', '0013_merge_20260726_2045'),
    ]

    operations = [
    ]
